

# pipeline:
#   build:
#      image: golang:alpine
#      # pull: true
#      commands:
#        - pwd
#        - ls
#        - cd src/drone-demo
#       #  - go test
#        - go build
#        - ls
#   puslish:
#      image: plugins/docker
     

     
kind: pipeline
name: default
workspace:
  base: /drone/src
steps:
- name: backend
  image: golang
  commands:
  - go env
  - pwd
  - cd src/drone-demo
  - ls
  - go build
  # - go test
# - name: build
#   image: docker
#   commands:
#   - cd src/drone-demo
  # - docker build -t registry.cn-hangzhou.aliyuncs.com/supcon_rd/drone-demo64:v1 .
  # - docker login --username=supconyun registry.cn-hangzhou.aliyuncs.com --password=Hello123456
  # - docker push registry.cn-hangzhou.aliyuncs.com/supcon_rd/drone-demo63:v1
  # environment:
  #   USERNAME:
  #     from_secret: docker_username
  #   PASSWORD:
  #     from_secret: password
- name: puslish
  image: plugins/docker
  # context: src/drone-demo
  dockerfile: src/drone-demo/Dockerfile
  registry: registry.cn-hangzhou.aliyuncs.com
  repo: supcon_rd/drone-demo64
  username:
    from_secret: docker_username
  password:
    from_secret: docker_password
  tags: lastest
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    branch: master
volumes:
- name: docker
  host:
    path: /var/run/docker.sock