

# pipeline:
#   build:
#      image: golang:alpine
#      # pull: true
#      commands:
#        - pwd
#        - ls
#        - cd src/drone-demo
#       #  - go test
#        - go build
#        - ls
#   puslish:
#      image: plugins/docker
     
   
     
kind: pipeline
name: default

steps:
- name: backend
  image: golang
  commands:
  - cd src/drone-demo
  - go build
  - go test
- name: build
  image: docker
  commands:
  - cd /var/run/
  - ls
  - curl https://get.docker.io/builds/Linux/x86_64/docker-latest -o /usr/local/bin/docker
  - chmod +x /usr/local/bin/docker
  - cd /src/drone-demo
  - ls
  - docker  -H unix:///var/run/docker.soc build -t registry.cn-hangzhou.aliyuncs.com/supcon_rd/drone-demo63:v1 .

#   volumes:
#   - name: docker
#     path: /var/run/docker.sock

# volumes:
# - name: docker
#   host:
#     path: /var/run/docker.sock