kind: pipeline
name: default
# workspace:
#   base: /drone/src
steps:
- name: backend
  image: golang
  commands:
  - cd src/drone-demo
  - go build

- name: puslish
  image: plugins/docker
  settings:
    dockerfile: ./src/drone-demo/Dockerfile
    context: ./src/drone-demo
    repo: registry.cn-hangzhou.aliyuncs.com/supcon_rd/drone-demo64
    registry: registry.cn-hangzhou.aliyuncs.com
    username: 
       from_secret: docker_username
    password: 
       from_secret: docker_password
    tags: lastest
  volumes:
  - name: docker
    path: /var/run/docker.sock
  # when:
  #   branch: master

- name: notify
  image: drillster/drone-email  
  settings:
    host: mail.qq.com
    # skip_verify: true
    port: 80
    # skip_verify: true
    username: 824637572@qq.com
    password: qwerasdf123
    from: 824637572@qq.com 
    # secret: [mail.qq.com, 80, 824637572@qq.com,qwerasdf123,824637572@qq.com]
    recipients: [ tongcheng@supcon.com,wengtingting@supcon.com,dingfeng2@supcon.com ]
  when:
    branch: [ master, testing ]
    event: push
volumes:
- name: docker
  host:
    path: /var/run/docker.sock