

pipeline:
  build:
     image: golang:alpine
     # pull: true
     commands:
       - pwd
       - ls
       - cd src/drone-demo
      #  - go test
       - go build
       - docker build -t demo63:v1 .